import {
  buildInitialDecisions,
  buildInitialState,
  toggleDecision,
  editFinding,
  buildSubmission,
  summariseDecisions,
  formatGitHubComment,
  formatApprovalComment,
} from '../src/agents/pr-review/approval'
import type { PRReview, Finding } from '../src/agents/pr-review/schema'

function makeFinding(overrides: Partial<Finding> = {}): Finding {
  return {
    id: overrides.id ?? 'f-' + Math.random().toString(36).slice(2),
    severity: overrides.severity ?? 'SUGGESTION',
    category: overrides.category ?? 'CORRECTNESS',
    file: overrides.file ?? 'src/foo.ts',
    title: overrides.title ?? 'Test finding',
    body: overrides.body ?? 'Description',
    confidence: overrides.confidence ?? 0.8,
    line: overrides.line,
  }
}

const blocking = makeFinding({
  id: 'b1',
  severity: 'BLOCKING',
  title: 'Blocking finding',
})
const suggestion = makeFinding({
  id: 's1',
  severity: 'SUGGESTION',
  title: 'Suggestion finding',
})
const nit = makeFinding({ id: 'n1', severity: 'NIT', title: 'Nit finding' })

const review: PRReview = {
  reviewId: 'rev-1',
  prUrl: 'https://github.com/owner/repo/pull/1',
  summary: 'Good PR',
  fileCoverage: [],
  ticketAlignment: [
    { requirement: 'Save without posting', met: true, location: 'finalize' },
  ],
  whatLooksGood: ['Clean code'],
  blockingIssues: [blocking],
  suggestions: [suggestion],
  nits: [nit],
  questions: ['Why skip the migration?'],
  testingRecommendations: ['Run unit tests'],
  verdict: 'REQUEST_CHANGES',
  verdictSummary: 'Fix the blocking issue before merging.',
  confidence: 0.85,
}

describe('buildInitialDecisions', () => {
  it('defaults BLOCKINGs and SUGGESTIONs to ACCEPT', () => {
    const decisions = buildInitialDecisions(review)
    expect(decisions['b1'].action).toBe('ACCEPT')
    expect(decisions['s1'].action).toBe('ACCEPT')
  })

  it('defaults NITs to REJECT', () => {
    const decisions = buildInitialDecisions(review)
    expect(decisions['n1'].action).toBe('REJECT')
  })
})

describe('toggleDecision', () => {
  it('toggles ACCEPT → REJECT', () => {
    const state = buildInitialState(review)
    const next = toggleDecision(state, 'b1')
    expect(next.decisions['b1'].action).toBe('REJECT')
  })

  it('toggles REJECT → ACCEPT', () => {
    const state = buildInitialState(review)
    const after = toggleDecision(state, 'n1') // NIT starts REJECT
    expect(after.decisions['n1'].action).toBe('ACCEPT')
  })

  it('toggles EDIT → REJECT (does not promote back to ACCEPT)', () => {
    let state = buildInitialState(review)
    state = editFinding(state, 'b1', 'my fix') // ACCEPT → EDIT
    const after = toggleDecision(state, 'b1') // EDIT → REJECT
    expect(after.decisions['b1'].action).toBe('REJECT')
  })

  it('returns state unchanged for unknown findingId', () => {
    const state = buildInitialState(review)
    const next = toggleDecision(state, 'nonexistent')
    expect(next).toEqual(state)
  })
})

describe('editFinding', () => {
  it('sets action to EDIT and stores editedBody', () => {
    const state = buildInitialState(review)
    const next = editFinding(state, 'b1', 'My custom fix text')
    expect(next.decisions['b1'].action).toBe('EDIT')
    expect(next.decisions['b1'].editedBody).toBe('My custom fix text')
  })
})

describe('buildSubmission', () => {
  it('includes all decisions in the submission', () => {
    const state = buildInitialState(review)
    const sub = buildSubmission(state, false)
    expect(sub.reviewId).toBe('rev-1')
    expect(sub.decisions).toHaveLength(3)
    expect(sub.postToGitHub).toBe(false)
  })

  it('sets postToGitHub=true when requested', () => {
    const state = buildInitialState(review)
    expect(buildSubmission(state, true).postToGitHub).toBe(true)
  })
})

describe('summariseDecisions', () => {
  it('counts accepted blocking findings', () => {
    const state = buildInitialState(review)
    const summary = summariseDecisions(review, state)
    expect(summary.blockingAccepted).toBe(1)
    expect(summary.accepted).toBe(2) // blocking + suggestion (nit is REJECT)
    expect(summary.rejected).toBe(1)
  })

  it('counts edited decisions as accepted', () => {
    let state = buildInitialState(review)
    state = editFinding(state, 's1', 'edited')
    const summary = summariseDecisions(review, state)
    expect(summary.edited).toBe(1)
    expect(summary.accepted).toBe(2) // blocking accepted + suggestion edited
  })
})

describe('formatGitHubComment', () => {
  it('includes verdict and summary in the output', () => {
    const state = buildInitialState(review)
    const sub = buildSubmission(state, true)
    const comment = formatGitHubComment(review, sub)
    expect(comment).toContain('REQUEST_CHANGES')
    expect(comment).toContain('Fix the blocking issue')
    expect(comment).toContain('Good PR')
    expect(comment).toContain('Generated by Agamotto')
  })

  it('includes accepted blocking findings', () => {
    const state = buildInitialState(review)
    const sub = buildSubmission(state, true)
    const comment = formatGitHubComment(review, sub)
    expect(comment).toContain('🔴 Blocking Issues')
  })

  it('includes each finding confidence percent next to the file location', () => {
    const withLine = makeFinding({
      id: 'b1',
      severity: 'BLOCKING',
      title: 'Blocking finding',
      file: 'app/route.ts',
      line: 183,
      confidence: 0.65,
    })
    const withLineReview: PRReview = {
      ...review,
      blockingIssues: [withLine],
    }
    const comment = formatGitHubComment(
      withLineReview,
      buildSubmission(buildInitialState(withLineReview), true)
    )
    expect(comment).toContain(
      '**Blocking finding** (`app/route.ts:183`, 65% confidence)'
    )
    expect(comment).toContain(
      '**Suggestion finding** (`src/foo.ts`, 80% confidence)'
    )
  })

  it('includes testing recommendations', () => {
    const state = buildInitialState(review)
    const sub = buildSubmission(state, true)
    const comment = formatGitHubComment(review, sub)
    expect(comment).toContain('Run unit tests')
  })

  it('omits nit section when nit is not accepted (default)', () => {
    const state = buildInitialState(review) // nit defaults to REJECT
    const sub = buildSubmission(state, true)
    const comment = formatGitHubComment(review, sub)
    expect(comment).not.toContain('💬 Nits')
    expect(comment).not.toContain('Nit finding')
  })

  it('includes accepted nit in a Nits section', () => {
    let state = buildInitialState(review)
    // Override the nit to ACCEPT
    state = toggleDecision(state, 'n1') // REJECT → ACCEPT
    const sub = buildSubmission(state, true)
    const comment = formatGitHubComment(review, sub)
    expect(comment).toContain('💬 Nits')
    expect(comment).toContain(nit.title)
  })

  it('omits nit section entirely when no nits exist on the review', () => {
    const noNitReview: PRReview = { ...review, nits: [] }
    const state = buildInitialState(noNitReview)
    const sub = buildSubmission(state, true)
    const comment = formatGitHubComment(noNitReview, sub)
    expect(comment).not.toContain('💬 Nits')
  })

  it('omits preamble, what-looks-good, and testing when those sections are REJECT', () => {
    const state = buildInitialState(review)
    const sub = {
      ...buildSubmission(state, true),
      sections: [
        { section: 'PREAMBLE' as const, action: 'REJECT' as const },
        { section: 'WHAT_LOOKS_GOOD' as const, action: 'REJECT' as const },
        {
          section: 'TESTING_RECOMMENDATIONS' as const,
          action: 'REJECT' as const,
        },
        { section: 'TICKET_ALIGNMENT' as const, action: 'REJECT' as const },
        { section: 'QUESTIONS' as const, action: 'REJECT' as const },
      ],
    }
    const comment = formatGitHubComment(review, sub)
    expect(comment).toContain('## AI PR Review — REQUEST_CHANGES')
    expect(comment).not.toContain('Fix the blocking issue')
    expect(comment).not.toContain('Good PR')
    expect(comment).not.toContain('What Looks Good')
    expect(comment).not.toContain('Clean code')
    expect(comment).not.toContain('Testing Recommendations')
    expect(comment).not.toContain('Run unit tests')
    expect(comment).not.toContain('Save without posting')
    expect(comment).not.toContain('Why skip the migration')
  })

  it('places AC alignment after the preamble and questions before testing', () => {
    const state = buildInitialState(review)
    const comment = formatGitHubComment(review, buildSubmission(state, true))
    const ac = comment.indexOf('### Acceptance Criteria alignment')
    const findings = comment.indexOf('### 🔴 Blocking Issues')
    const looksGood = comment.indexOf('### ✅ What Looks Good')
    const questions = comment.indexOf('### Questions')
    const testing = comment.indexOf('### 🧪 Testing Recommendations')
    expect(ac).toBeGreaterThan(-1)
    expect(ac).toBeLessThan(findings)
    expect(looksGood).toBeGreaterThan(findings)
    expect(questions).toBeGreaterThan(looksGood)
    expect(testing).toBeGreaterThan(questions)
    expect(comment).toContain('[x] Save without posting — finalize')
    expect(comment).toContain('Why skip the migration?')
  })

  it('uses edited section bodies when sections are EDIT', () => {
    const state = buildInitialState(review)
    const sub = {
      ...buildSubmission(state, true),
      sections: [
        {
          section: 'PREAMBLE' as const,
          action: 'EDIT' as const,
          editedBody: 'Rewritten intro.',
        },
        {
          section: 'WHAT_LOOKS_GOOD' as const,
          action: 'EDIT' as const,
          editedBody: 'Great tests',
        },
        {
          section: 'TESTING_RECOMMENDATIONS' as const,
          action: 'EDIT' as const,
          editedBody: '- Hit the new endpoint',
        },
      ],
    }
    const comment = formatGitHubComment(review, sub)
    expect(comment).toContain('Rewritten intro.')
    expect(comment).not.toContain('Good PR')
    expect(comment).toContain('Great tests')
    expect(comment).not.toContain('Clean code')
    expect(comment).toContain('Hit the new endpoint')
    expect(comment).not.toContain('Run unit tests')
  })
})

describe('formatApprovalComment', () => {
  it('includes testing recommendations on a clean review', () => {
    const comment = formatApprovalComment({ ...review, blockingIssues: [] })
    expect(comment).toContain('Run unit tests')
    expect(comment).toContain('Good PR')
    expect(comment).toContain('Clean code')
  })

  it('omits excluded sections on a clean review', () => {
    const comment = formatApprovalComment({ ...review, blockingIssues: [] }, [
      { section: 'PREAMBLE' as const, action: 'REJECT' as const },
      { section: 'WHAT_LOOKS_GOOD' as const, action: 'REJECT' as const },
      {
        section: 'TESTING_RECOMMENDATIONS' as const,
        action: 'REJECT' as const,
      },
      { section: 'TICKET_ALIGNMENT' as const, action: 'REJECT' as const },
      { section: 'QUESTIONS' as const, action: 'REJECT' as const },
    ])
    expect(comment).toContain('APPROVED')
    expect(comment).not.toContain('Good PR')
    expect(comment).not.toContain('Clean code')
    expect(comment).not.toContain('Run unit tests')
    expect(comment).not.toContain('Save without posting')
    expect(comment).not.toContain('Why skip the migration')
  })
})
