/**
 * Client-side GitHub comment markdown from the review UI's Include/edit state.
 */

import {
  findingReviewAction,
  finalizeDecisionsFromUi,
  formatReviewCommentFromUi,
} from '../src/lib/review-comment-copy'
import type { Finding } from '../src/agents/pr-review/schema'
import { ReviewSection, hydrateSectionUi } from '../src/lib/review-sections'

function finding(overrides: Partial<Finding> = {}): Finding {
  return {
    id: overrides.id ?? 'f-1',
    severity: overrides.severity ?? 'SUGGESTION',
    category: overrides.category ?? 'CORRECTNESS',
    file: overrides.file ?? 'src/foo.ts',
    title: overrides.title ?? 'Suggestion finding',
    body: overrides.body ?? 'Description',
    confidence: overrides.confidence ?? 0.8,
    line: overrides.line,
    suggestedFix: overrides.suggestedFix,
  }
}

describe('findingReviewAction', () => {
  it('maps unchecked to REJECT', () => {
    expect(findingReviewAction({ accepted: false })).toBe('REJECT')
  })

  it('maps checked with no edits to ACCEPT', () => {
    expect(findingReviewAction({ accepted: true })).toBe('ACCEPT')
  })

  it('maps checked with an edited title or body to EDIT', () => {
    expect(
      findingReviewAction({ accepted: true, editedTitle: 'new title' })
    ).toBe('EDIT')
    expect(
      findingReviewAction({ accepted: true, editedBody: 'new body' })
    ).toBe('EDIT')
  })

  it('maps unchecked with leftover edits to REJECT', () => {
    expect(
      findingReviewAction({
        accepted: false,
        editedTitle: 'ignored',
        editedBody: 'ignored',
      })
    ).toBe('REJECT')
  })
})

describe('finalizeDecisionsFromUi', () => {
  it('maps the UI decision record into finalize payload actions', () => {
    expect(
      finalizeDecisionsFromUi({
        a: { findingId: 'a', accepted: true },
        b: {
          findingId: 'b',
          accepted: true,
          editedTitle: 't',
          editedBody: 'b',
        },
        c: { findingId: 'c', accepted: false },
      })
    ).toEqual([
      {
        findingId: 'a',
        action: 'ACCEPT',
        editedTitle: undefined,
        editedBody: undefined,
      },
      {
        findingId: 'b',
        action: 'EDIT',
        editedTitle: 't',
        editedBody: 'b',
      },
      {
        findingId: 'c',
        action: 'REJECT',
        editedTitle: undefined,
        editedBody: undefined,
      },
    ])
  })
})

describe('formatReviewCommentFromUi', () => {
  it('formats a clean review as an LGTM approval comment', () => {
    const markdown = formatReviewCommentFromUi({
      reviewId: 'rev-1',
      findings: [],
      decisions: {},
      extras: { summary: 'Looks solid.', whatLooksGood: ['Clear names'] },
    })
    expect(markdown).toContain('APPROVED')
    expect(markdown).toContain('Looks solid.')
    expect(markdown).toContain('Clear names')
    expect(markdown).toContain('Generated by Agamotto')
  })

  it('includes accepted findings and omits rejected ones', () => {
    const blocking = finding({
      id: 'b1',
      severity: 'BLOCKING',
      title: 'Null deref',
      line: 12,
    })
    const suggestion = finding({ id: 's1', title: 'Skip me' })
    const markdown = formatReviewCommentFromUi({
      reviewId: 'rev-1',
      findings: [blocking, suggestion],
      decisions: {
        b1: { findingId: 'b1', accepted: true },
        s1: { findingId: 's1', accepted: false },
      },
    })
    expect(markdown).toContain('Null deref')
    expect(markdown).toContain('src/foo.ts:12')
    expect(markdown).toContain('80% confidence')
    expect(markdown).not.toContain('Skip me')
  })

  it('uses edited title and body for an included finding', () => {
    const f = finding({ id: 's1', title: 'old title', body: 'old body' })
    const markdown = formatReviewCommentFromUi({
      reviewId: 'rev-1',
      findings: [f],
      decisions: {
        s1: {
          findingId: 's1',
          accepted: true,
          editedTitle: 'new title',
          editedBody: 'new body',
        },
      },
    })
    expect(markdown).toContain('new title')
    expect(markdown).toContain('new body')
    expect(markdown).not.toContain('old title')
    expect(markdown).not.toContain('old body')
  })

  it('includes an accepted nit and a suggested fix', () => {
    const nit = finding({
      id: 'n1',
      severity: 'NIT',
      title: 'Rename foo',
      suggestedFix: 'call it bar',
    })
    const markdown = formatReviewCommentFromUi({
      reviewId: 'rev-1',
      findings: [nit],
      decisions: { n1: { findingId: 'n1', accepted: true } },
    })
    expect(markdown).toContain('💬 Nits')
    expect(markdown).toContain('Rename foo')
    expect(markdown).toContain('call it bar')
  })

  it('prefers a stored verdict over the derived one', () => {
    const markdown = formatReviewCommentFromUi({
      reviewId: 'rev-1',
      findings: [finding({ id: 'b1', severity: 'BLOCKING' })],
      decisions: { b1: { findingId: 'b1', accepted: true } },
      extras: { verdict: 'COMMENT' },
    })
    expect(markdown).toContain('## AI PR Review — COMMENT')
    expect(markdown).not.toContain('REQUEST_CHANGES')
  })

  it('uses stored extras when present', () => {
    const markdown = formatReviewCommentFromUi({
      reviewId: 'rev-1',
      findings: [finding({ id: 's1' })],
      decisions: { s1: { findingId: 's1', accepted: true } },
      extras: {
        summary: 'Overall good',
        verdict: 'COMMENT',
        verdictSummary: 'A few nits',
        whatLooksGood: ['Tests'],
        testingRecommendations: ['Run npm test'],
        questions: ['Why this approach?'],
        ticketAlignment: [{ requirement: 'Save without posting', met: true }],
      },
    })
    expect(markdown).toContain('## AI PR Review — COMMENT')
    expect(markdown).toContain('Overall good')
    expect(markdown).toContain('A few nits')
    expect(markdown).toContain('Tests')
    expect(markdown).toContain('Run npm test')
    expect(markdown).toContain('Why this approach?')
    expect(markdown).toContain('Save without posting')
  })

  it('omits excluded extras sections from the copied comment', () => {
    const extras = {
      summary: 'Overall good',
      verdict: 'COMMENT' as const,
      whatLooksGood: ['Tests'],
      testingRecommendations: ['Run npm test'],
    }
    const markdown = formatReviewCommentFromUi({
      reviewId: 'rev-1',
      findings: [finding({ id: 's1' })],
      decisions: { s1: { findingId: 's1', accepted: true } },
      extras,
      sections: {
        ...hydrateSectionUi(extras),
        [ReviewSection.PREAMBLE]: {
          section: ReviewSection.PREAMBLE,
          accepted: false,
        },
        [ReviewSection.WHAT_LOOKS_GOOD]: {
          section: ReviewSection.WHAT_LOOKS_GOOD,
          accepted: false,
        },
        [ReviewSection.TESTING_RECOMMENDATIONS]: {
          section: ReviewSection.TESTING_RECOMMENDATIONS,
          accepted: true,
          editedBody: 'Hit /health',
        },
      },
    })
    expect(markdown).not.toContain('Overall good')
    expect(markdown).not.toContain('Tests')
    expect(markdown).toContain('Hit /health')
    expect(markdown).not.toContain('Run npm test')
  })

  it('derives REQUEST_CHANGES when an accepted blocking has no stored verdict', () => {
    const markdown = formatReviewCommentFromUi({
      reviewId: 'rev-1',
      findings: [finding({ id: 'b1', severity: 'BLOCKING' })],
      decisions: { b1: { findingId: 'b1', accepted: true } },
    })
    expect(markdown).toContain('REQUEST_CHANGES')
  })

  it('derives COMMENT when no accepted blocking remains', () => {
    const markdown = formatReviewCommentFromUi({
      reviewId: 'rev-1',
      findings: [finding({ id: 'b1', severity: 'BLOCKING' })],
      decisions: { b1: { findingId: 'b1', accepted: false } },
    })
    expect(markdown).toContain('## AI PR Review — COMMENT')
  })

  it('treats a missing decision as included', () => {
    const markdown = formatReviewCommentFromUi({
      reviewId: 'rev-1',
      findings: [finding({ id: 's1', title: 'Keep me' })],
      decisions: {},
    })
    expect(markdown).toContain('Keep me')
  })

  it('still formats a finding whose category is not a known enum value', () => {
    const markdown = formatReviewCommentFromUi({
      reviewId: 'rev-1',
      findings: [
        {
          id: 's1',
          severity: 'SUGGESTION',
          category: 'UNKNOWN',
          file: 'a.ts',
          title: 'Odd category',
          body: 'still copyable',
          confidence: 0.9,
        },
      ],
      decisions: { s1: { findingId: 's1', accepted: true } },
    })
    expect(markdown).toContain('Odd category')
  })
})
